spring.application.name=Orders
logging.pattern.console=%d{HH:mm:ss} [%thread] [%X{traceId}] %-5level %logger{36} - %msg%n
spring.datasource.url=jdbc:postgresql://db:5432/mydb
spring.datasource.username=postgres
spring.datasource.password=dev
spring.jpa.hibernate.ddl-auto=update